name: CI TP Noté

on:
  push:
    branches: [develop]

jobs:
  test-memory-2026:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test JPEG
        run: |
          for file in $(find . -type f \( -name "*.jpg" -o -name "*.jpeg" \)); do
            file "$file"
          done
    
  build-memory-2026:
    needs: test-memory-2026
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/memory-2026:latest .


  puush-memory-2026:
    needs: build-memory-2026
    runs-on: self-hosted
    steps:
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Push the image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: docker.io/${{ secrets.DOCKER_USERNAME }}/memory-2026:latest

  deploy-memory-2026:
    needs: puush-memory-2026
    runs-on: self-hosted
    steps:
    - name: Pull docker image
      run: docker pull iwtpl/memory-2026:latest

    - name: Build the container
      run: docker run -d \
          --name memory \
          -p 8080:80 \
          iwtpl/memory-2026:latest

     
